galaxy_info:
  author: Thomas Krag
  description: An Ansible role to easily clean disks.
  compall: Cultivated Ops

  issue_tracker_url: https://jira.cultivatedops.com/projects/ANSIBLE/

  license: Apache

  min_ansible_version: 1.9

  github_branch: master

  platforms:
    - name: EL
      versions:
        - all

    - name: GenericUNIX
      versions:
        - all

    - name: OpenBSD
      versions:
        - all

    - name: Fedora
      versions:
        - all

    - name: opensuse
      versions:
        - all

    - name: MacOSX
      versions:
        - all

    - name: IOS
      versions:
        - all

    - name: Solaris
      versions:
        - all

    - name: SmartOS
      versions:
        - all

    - name: eos
      versions:
        - all

    - name: Windows
      versions:
        - all

    - name: Amazon
      versions:
        - all

    - name: GenericBSD
      versions:
        - all

    - name: Junos
      versions:
        - all

    - name: FreeBSD
      versions:
        - all

    - name: Ubuntu
      versions:
        - all

    - name: SLES
      versions:
        - all

    - name: GenericLinux
      versions:
        - all

    - name: NXOS
      versions:
        - all

    - name: Debian
      versions:
        - all

  galaxy_tags:
    - cultivatedops
    - disk
    - cleanup
    - filesystem

dependencies: []
