---

  config:
    verbosity_level: 2
    selinux_level: permissive
    selinux_policy: targeted # reqired if `selinux_level` is not `disabled`
    build_information:
      src: ../build-information.j2.txt
      dest: /home/centos/build-information.txt

  packages:
    os:
      - bind-utils
      - curl
      - git
      - htop
      - jq
      - mc
      - mlocate
      - screen
      - telnet
      - tree
