---

  config:
    verbosity_level: 2
    selinux_level: permissive
    selinux_policy: targeted # reqired if `selinux_level` is not `disabled`
    build_information:
      src: ../build-information.j2.txt
      dest: /home/centos/build-information.txt

  packages:
    yum:
      base:
        -
          name: bind-utils
          version: latest
        -
          name: curl
          version: latest
        -
          name: git
          version: latest
        -
          name: htop
          version: latest
        -
          name: jq
          version: latest
        -
          name: man
          version: latest
        -
          name: mc
          version: latest
        -
          name: mlocate
          version: latest
        -
          name: nano
          version: latest
        -
          name: python2-pip
          version: latest
        -
          name: rsync
          version: latest
        -
          name: screen
          version: latest
        -
          name: telnet
          version: latest
        -
          name: tree
          version: latest
        -
          name: vim-enhanced
          version: latest
        -
          name: wget
          version: latest
    pip:
      base:
        -
          name: awscli
          version: latest
