---

- name: provisioning base
  hosts: packer
  become: true
  remote_user: centos
  vars_files:
    - ../vars/config.yml

  roles:
    # output some debug information
    - role: debug
      vars:
        verbosity_level: "{{ config.verbosity_level }}"

  tasks:
    - name: set build information
      template:
        dest: "{{ config.build_information.dest }}"
        force: true
        src: "{{ config.build_information.src }}"

    - name: set SELinux policy
      selinux:
        policy: "{{ config.selinux_policy | default(omit) }}"
        state: "{{ config.selinux_level }}"
      tags:
        - selinux

    - name: enable EPEL repository
      yum:
        name: "epel-release"
        state: latest
      tags:
        - yum
        - yum_epel

    - name: install base YUM Packages
      yum:
        name: "{{ item.name }}"
        state: "{{ item.version | default('latest')}}"
      with_items: "{{ packages.yum.base }}"
      tags:
        - yum
        - yum_base

    - name: update all installed YUM packages to latest version
      yum:
        name: "*"
        state: latest
      tags:
        - yum_update_all

    - name: install base `pip` Packages
      pip:
        name: "{{ item.name }}"
        state: "{{ item.version | default('latest')}}"
      with_items: "{{ packages.pip.base }}"
      tags:
        - pip
        - pip_base

    - name: upgrade `pip` to latest version
      pip:
        name: pip
        state: latest
      tags:
        - pip
        - pip_upgrade

  post_tasks:
    - name: clean YUM cache
      command: yum clean all

  #   - name: clean disk
  #     include: ./roles/diskcleanup/tasks/main.yml
