---

- name: provisioning base
  hosts: packer
  become: true
  remote_user: centos
  vars_files:
    - ../vars/config.yml

  roles:
    # output some debug information
    - role: debug
      vars:
        verbosity_level: "{{ config.verbosity_level }}"

  tasks:
    - name: set build information
      template:
        dest: "{{ config.build_information.dest }}"
        force: true
        src: "{{ config.build_information.src }}"

    - name: set SELinux policy
      selinux:
        policy: "{{ config.selinux_policy | default(omit) }}"
        state: "{{ config.selinux_level }}"
      tags:
        - selinux

    - name: enable EPEL repository
      yum:
        name: "epel-release"
        state: latest
      with_items: "{{ packages.os }}"
      tags:
        - yum
        - yum_epel

    - name:
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ packages.os }}"
      tags:
        - yum
        - yum_base

    - name: update all installed packages to latest version
      yum:
        name: "*"
        state: latest
      tags:
        - yum_update_all

  # post_tasks:
  #   - name: clean disk 
  #     include: ./roles/diskcleanup/tasks/main.yml
