---

- name: prepping Ansible Control for Packer
  gather_facts: false
  hosts: localhost

  tasks:
    - name: installing Ansible role(s)
      command: >
        ansible-galaxy
          --roles-path="{{ roles_path }}"
          --role-file="{{ role_file }}"
          install
