---

- name: provisioning base
  hosts: packer
  become: true
  remote_user: centos
  vars_files:
    - ../vars/config.yml

  tasks:
    - debug:
        msg: "{{ ansible_user }}@{{ ansible_host }}:{{ ansible_port }}"

    - debug:
        msg: "key: {{ ansible_ssh_private_key_file }}"
